var json_XYSiguranta_seg_f_2 = {
"type": "FeatureCollection",
"name": "XYSiguranta_seg_f_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Latitudine": 44.44681, "Longitudin": 26.0737, "Tip_proiec": "Finan?are extern?", "Stadiu_in": "in pregatire", "Denumire_p": "Studiu de Fezabilitate  “Implementarea m?surilor necesare func?ion?rii sistemului ERTMS pe sec?iunea de cale ferat? Predeal-Bucure?ti-Constan?a ?i extinderea sistemului GSM-R pe re?eaua de transport feroviar”", "Denumire_o": "SF lucr?ri semnalizare ?i centralizare CF Predeal - Bucure?ti", "Localizare": "Predeal-Bucure?ti", "Nr__Linie": "300", "Sec_ia_de": "Predeal-Bucure?ti", "Lot": null, "Lungime__k": "143 km", "De_la_poz": "km  143+0,000", "Pana_la_po": "km 0+0,000", "Antrepreno": "Baicons Impex S.R.L.", "Data_înce": "2020-03-11", "Data_final": "iul.22", "Stadiu_fiz": "15%", "Stadiu__fi": "15%", "Observa_ii": "SF în derulare.\nValoare contract: 4.477.000 lei fara TVA", "Latitudi_1": "4.550.637", "Longitud_1": "2.557.559", "Latitudi_2": 4.55, "Longitud_2": 2.557, "Latitudi_3": "4.444.681", "Longitud_3": "2.607.370", "Latitudi_4": 4.444, "Longitud_4": 2.607, "Detalii_pr": "NA" }, "geometry": { "type": "Point", "coordinates": [ 26.0737, 44.44681 ] } },
{ "type": "Feature", "properties": { "Latitudine": 44.16877, "Longitudin": 28.63165, "Tip_proiec": "Finan?are extern?", "Stadiu_in": "in pregatire", "Denumire_p": "Studiu de Fezabilitate  “Implementarea m?surilor necesare func?ion?rii sistemului ERTMS pe sec?iunea de cale ferat? Predeal-Bucure?ti-Constan?a ?i extinderea sistemului GSM-R pe re?eaua de transport feroviar”", "Denumire_o": "SF lucr?ri semnalizare ?i centralizare CF Bucure?ti - Constan?a", "Localizare": "Bucure?ti-Constan?a", "Nr__Linie": "800", "Sec_ia_de": "Bucure?ti - Constan?a", "Lot": null, "Lungime__k": "224 km", "De_la_poz": "km 0+0,000", "Pana_la_po": "km  224+000", "Antrepreno": "Baicons Impex S.R.L.", "Data_înce": "2020-03-11", "Data_final": "iul.22", "Stadiu_fiz": "15%", "Stadiu__fi": "15%", "Observa_ii": "SF în derulare.\nValoare contract: 4.477.000 lei fara TVA", "Latitudi_1": "4.444.681", "Longitud_1": "2.607.370", "Latitudi_2": 4.444, "Longitud_2": 2.607, "Latitudi_3": "4.416.877", "Longitud_3": "2.863.165", "Latitudi_4": 4.416, "Longitud_4": 2.863, "Detalii_pr": null }, "geometry": { "type": "Point", "coordinates": [ 28.63165, 44.16877 ] } }
]
}
